spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
