spring:
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    
jwt:
  secret: mySuperSecretKeyForJWT123456789
  expiration: 3600000  # 1 hour

